### ISSUE TITLE
File names not recognized 

### ISSUE THREAD

**Issue by productboy** [acucciniello/alexa-open-doc#3]
Alexa doesn't recognize file name when creating a new one; defaults to 'untitled'. Then when trying to edit Alexa doesn't recognize the untitled file name.

**Comment by acucciniello** [comment]
@productboy thank you for letting me know about this.  Could you send me a screenshot of what you said to invoke Alexa and Alexa's response to aid me in debugging this?

**Comment by productboy** [comment]
Since I 'spoke' to the Alexa device [we have a few, this one is also a Bluetooth speaker] there's no screenshot.

My spoken words were:
"Alexa ask Edit Docs to create a file named test"

**Comment by acucciniello** [comment]
Ok thank you I will start working on a solution for this right now!

**Comment by acucciniello** [comment]
@productboy 
Ok so I think I was able to solve this but I will wait for your feedback on this.  What happened here was the example phrase that Alexa knew to follow in order to create a file was
"Alexa ask Edit Docs to create a file *called* test"
When you said 'named' instead of 'called' it automatically included 'named test' as the file name without a file type.  So it had trouble handling that.  Now I added 'named' in as part of the example phrases so It should be able to handle it.  Once you test it out let me know if it works for you and I will close this issue.  Also if this skill serves you well I would love a review on [amazon](https://www.amazon.com/Antonio-Cucciniello-Edit-Docs/dp/B01MYOGRD5)!

**Comment by acucciniello** [comment]
Sorry I have to wait for the skill to be re-published so allow a day to a week for that and it should be updated with the fix.

**Comment by productboy** [comment]
Antonio,
Will test the fix tonite.  Thanks for jumping on this.

**Comment by acucciniello** [comment]
Unfortunately, Amazon is taking a little while to approve the update, so as of now, the skill will not function differently until my skill passes their verification, hopefully, it will be sooner rather than later @productboy

**Comment by acucciniello** [comment]
@productboy It was approved last night go ahead and try it out!

**Comment by acucciniello** [comment]
@productboy Do you have an update if this worked for you? I would like to establish this issue as resolved if it worked! If not I will take any feedback you have.
